version: "3"
services:
  web:
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - NODE_ENV=production

    restart: always
    build: .
    depends_on:
      - redis
    ports:
      - "3000:3000"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voting_prod
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0
    # ports:
    #   - "6379:6379"
