version: "3"
services:
  web:
    environment:
    - REDIS_PORT=6379
    - REDIS_HOST=redis
    
    restart: always
    build: .
    depends_on: 
      - redis
    ports:
      - "3000:3000"
    
  redis:
    image: redis:7.0
    # ports:
    #   - "6379:6379"
